dist: trusty
language: cpp
compiler: gcc

addons:
  apt:
    packages:
    - cmake
    - libboost-dev
    - protobuf-compiler
    - libprotobuf-dev
    - libnl-3-dev
    
script:
- cmake .
- make
- make package
